### ISSUE TITLE
Albums Library Appears Empty

### ISSUE THREAD

**Issue by t-miller** [Xeroday/Spotify-Ad-Blocker#181]
__Spotify Version__: `1.0.92.390.g2ce5ec7d` & `1.0.93.244.g1e3a05e7`
__EZ Blocker Version__: `1.7.3`

I have a large amount of albums saved to my library that display properly on the web version of Spotify. They are no longer displaying on the desktop client.
![image](https://user-images.githubusercontent.com/19845698/48499009-78903f80-e805-11e8-977e-1585195b1ee9.png)

**Comment by Nitrooo** [comment]
Same here. Also, most "new" songs I never played in the past are not loading/playing and an empty album image appears instead of the actual album image. On the other hand, my favorite albums which I play a lot work just fine, even after having cleared the cache. Weird. All fine on my Android Spotify app.

**Comment by GenesisFR** [comment]
Had the same issue but on the Artist tab, some songs couldn't be played either. After 2 days, it seems to have resolved itself, must have been on Spotify's side.
