### ISSUE TITLE
Ads aren't muted but changing mid-song does mute the app

### ISSUE THREAD

**Issue by miermontoto** [Xeroday/Spotify-Ad-Blocker#190]
EZBlocker Version: 1.7.3.0
Spotify Version: 1.0.95.289

**Comment by thatguy344** [comment]
It used to be that Spotify devs sabotaging the tool's functionality was counter-balanced/fixed within a week or so at most but we haven't heard anything substantial for a while now from the dev, seems like with this latest patch they've really outdone themselves. Let's just hope this won't be the end of EzBlocker for the foreseeable future, afaik the new web player doesn't work with adblock enabled either

**Comment by GijonDev** [comment]
thanks for updating

**Comment by thepcwiz101** [comment]
@thatguy344 The spotify web player now requires drm to be enabled on your browser. With my testing it has to be well known browsers like chrome and firefox otherwise it will not work. They did this to stop people from stealing songs and using adblock. the desktop client still works but you need to use a batch file that patches your hosts file to block the ads completely. The only way they could stop us from blocking ads now is putting in code that checks the hosts file and throws an error about it and asks for you to remove listed entries to access spotify,

**Comment by Xeroday** [comment]
I'm able to get this to happen. 

What does the status on EZBlocker say when an ad is playing (and not muted) and when it's muting a regular song?

**Comment by luqtf** [comment]
> @thatguy344 The spotify web player now requires drm to be enabled on your browser. With my testing it has to be well known browsers like chrome and firefox otherwise it will not work. They did this to stop people from stealing songs and using adblock. the desktop client still works but you need to use a batch file that patches your hosts file to block the ads completely. The only way they could stop us from blocking ads now is putting in code that checks the hosts file and throws an error about it and asks for you to remove listed entries to access spotify,
> 
> Update: for some reason now when i use brave with ublock origin it blocks ads on open.spotify.com (spotify web player)

may i know how you patched out the hosts file?
