### ISSUE TITLE
The blocker hangs and stops responding for a few seconds when Spotify is closed w/o closing the blocker first

### ISSUE THREAD

**Issue by giacomodrago** [Xeroday/Spotify-Ad-Blocker#62]

**Comment by Xeroday** [comment]
EZBlocker should automatically open Spotify if its closed. Is EZBlocker completely unresponsive?

**Comment by stevek123** [comment]
I have exactly the same problem. If the app comes back to life (usually it doesn't), it's still laggy and hangs/freezing.

I think this error message has something to do with it (from EZBlocker-log.txt):
System.Net.WebException: A kérelmet megszakították: Időtúllépés történt a művelet végrehajtása során.
   a következő helyen: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   a következő helyen: System.Net.WebClient.DownloadString(Uri address)
   a következő helyen: EZBlocker.WebHelperHook.GetPage(String URL)
   a következő helyen: EZBlocker.WebHelperHook.GetStatus()
   a következő helyen: EZBlocker.Main.MainTimer_Tick(Object sender, EventArgs e)

**Comment by vmonkey** [comment]
EZBlocker does indeed open Spotify. The issue is about a situation that you have both Spotify and EZBlocker already (and successfully) running and you just want to quit Spotify (turn off music). Usually people may tend to forget about running EZBlocker and just close Spotify, which in this case leads to the situation that EZBlocker stopps responding. The solution may be that once EZBlocker finds out that Spotify is not running it should also quit itself.

**Comment by Xeroday** [comment]
The latest update should fix this issue.
