### ISSUE TITLE
Why programming in C# with .NET Framework 3.5?

### ISSUE THREAD

**Issue by VGH05T** [Xeroday/Spotify-Ad-Blocker#64]
Hi, i was thinking about porting it to other systems, but... C# and .net kinda makes it not so cool.
Why keep in this segment instead of going to a java? or even pure C (with NSPR lib)?

Thankz!

**Comment by tompazourek** [comment]
@VGH05T: EZBlocker is programmed very tightly with Win32 API. That's because operations like looking at other windows, muting the audio, disabling hostnames, and basically **everything that EZBlocker does**, are **very OS-specific**.

If you would want to port it to other platforms than Windows, my guess is that the programming language is a tiny obstacle compared to finding ways how to do these things on given OS.

---

Also note that you can still develop multi-platform SW in C#, take a look at popular [Banshee](https://github.com/GNOME/banshee) player, for example.

**Comment by VGH05T** [comment]
Thank you for the reply. 
I also saw the [mono-project](http://www.mono-project.com/) and the intention of microsoft of making [.net portable](https://github.com/Microsoft/dotnet)... but I think this will still take time to happen.
Anyway, would be usefull to port this EZBlocker to linu and OS X.

**Comment by Xeroday** [comment]
As tompazourek said, it doesn't matter which language EZBlocker is written in. EZBlocker invokes lower level calls and is OS dependent. The application itself is actually pretty simple and most of the work would be re-writing the muting functionality anyways.
