### ISSUE TITLE
EZBlocker stopped working

### ISSUE THREAD

**Issue by bobob15** [Xeroday/Spotify-Ad-Blocker#82]
I have this message “ezblocker stopped working”
Windows 10, Spotify 1.0.28.87, and EZBlocker 1.6.6.1

Please help me ! :-) 
Thanks

**Comment by jostidetosti** [comment]
You could try using ezblocker version 1.5 instead of 1.6

**Comment by bobob15** [comment]
I have already tried several versions but without results...
Sorry for my English, I am French

**Comment by Xeroday** [comment]
Can you post the contents of the EZBlocker-log.txt file? It should be in the same folder you saved EZBlocker.exe.

**Comment by CHEF-KOCH** [comment]
I'm on 1.0.29.90 g200ff544 and it works quite good. :+1: Nice little program, thanks for this.

**Comment by Frazew** [comment]
I don't if the error these people are getting is the same as the one I got but for me EZBlocker kept crashing when launched without writing anything to the log file. The error was on the dll "AUDIOSES.DLL". I couldn't find any fix for until until now. I use Razer Surround, this created a new virtual audio output which is then activated and selected as the default output. When I switched to my real audio output (ie. the one provided by the Realtek audio driver), EZBlocker started without any issue and worked just fine.

**Comment by CHEF-KOCH** [comment]
Frazew, thanks but this is not really related to it, the issue you had is self-made, since OP not mentioned this I guess he/she really talks about the EZBlocker itself. Anyway thanks for the hint. 

I guess we can close this, I can't confirm this on latest Spotify + I'm also use Win 10. I also tried in a VM older Versions of Spotify but EZBlocker works well. 

The only stuff which was changed are bugfixes and protocol related things in recent Spotify versions.

**Comment by WondersBorn** [comment]
I'm also experiencing this problem, using the lastest version, on Win10 and Spotify 1.0.33.106.g60b5d1f0.
Compiling and running from source also results in a crash, with this error:

"The program '[12160] EZBlocker.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'."

But like @Frazew said, this seems to be an audio incompatibility issue, because it only happens with my headphones as default audio device, if I use the monitor speakers, it works well.
