### ISSUE TITLE
Ad-banner not showing but takes place

### ISSUE THREAD

**Issue by XakFak** [Xeroday/Spotify-Ad-Blocker#92]
![image](https://cloud.githubusercontent.com/assets/20165408/19076972/6eb4e202-8a53-11e6-8e95-3a592d6ce65e.png)
By this setting i can use spotify without any ads at all audio/video/banner even if i close EZBlocker. Nice job man! But i get that blank banner place which is kinda annoying. So can you take a look at this if u have some time. Bthw thx a lot for your work.
![spotify](https://cloud.githubusercontent.com/assets/20165408/19076932/47fd4d16-8a53-11e6-9bcd-fb0b9a15ba7f.png)

**Comment by elieobeid7** [comment]
I just want to confirm that bug on my pc, without having the second checkbox ticked.

**Comment by CHEF-KOCH** [comment]
* https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Spotify-opens-webrowser-firefox-with-ads/td-p/1461029 
* http://www.ghacks.net/2016/10/05/spotify-free-opens-web-browser-ads/

**Comment by elieobeid7** [comment]
@CHEF-KOCH  in my opinion, if Spotify-Ad-Blocker isn't able to block banners, then it should show them, I use the adblocker to block audio ads and I care less about the banners because I have spotify minimized most of the time. 

Seeing an ad banner is better than seeing a black square. I might like the ad banner if the advertiser if advertising cool stuff, but I certainly hate a black square, it's so annoying.

**Comment by AInj** [comment]
EZBlocker uses non-intrusive methods and does not modify the Spotify client in any way. It prevents the ad data from reaching your Spotify client so it doesn't show but cannot actually remove the entire block as it's hardcoded inside Spotify itself.

There's no non-intrusive way to remove that block and I believe it should remain as it is.

**Comment by Xeroday** [comment]
If you want to see the ads, perhaps you shouldn't be using an ad-blocker. You can also uncheck the "Disable all ads" checkbox and restart your computer to see the banner ads again.
